### PR TITLE
﻿Add support for permanent file logging appender

### PR DESCRIPTION
**Pull request by mirko-bianco**

### CODE REVIEW

**Review by sonjli — COMMENTED** [review]
Sorry, I never used the spring logger. I'll try it soon.
So, I can't help to review this change.

**Review by BasvRossem — CHANGES_REQUESTED** [review]
If I am not mistaken, it seems to me that it is possible to do a DoSend while no stream has been created. 
I would advise you to create a default stream in the Create (like the TStreamLogger does), or to implement a DoSend that checks if the stream is assigned before calling the inherited DoStream

**Comment by mirko-bianco** [comment]
> If I am not mistaken, it seems to me that it is possible to do a DoSend while no stream has been created. 
> I would advise you to create a default stream in the Create (like the TStreamLogger does), or to implement a DoSend that checks if the stream is assigned before calling the inherited DoStream

Thought about that too.
BUT this class is to be used in conjunction with the Spring logging system, and as far as I can see there is no way anything can be logged before the filename is set.

**Comment by BasvRossem** [comment]
Just tested it and you seem to be correct 😄

**Review by BasvRossem — APPROVED** [review]

**Pull request merged**
